package com.example.safesteps;
import android.accessibilityservice.AccessibilityService; import android.content.Intent; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.os.Handler; import android.view.*; import android.view.accessibility.AccessibilityEvent; import android.widget.*; import java.util.List; import java.util.Locale;
public class GuardAccessibilityService extends AccessibilityService {
 private final Handler handler=new Handler(); private WindowManager wm; private View overlay; private boolean blocking;
 public void onServiceConnected(){super.onServiceConnected();wm=(WindowManager)getSystemService(WINDOW_SERVICE);}
 public void onAccessibilityEvent(AccessibilityEvent e){if(e==null||!getSharedPreferences(MainActivity.PREFS,0).getBoolean(MainActivity.ENABLED,false))return;String pkg=String.valueOf(e.getPackageName());if(getPackageName().equals(pkg))return;if(isForbidden(e,pkg))blockCurrentScreen();}
 private boolean isForbidden(AccessibilityEvent e,String pkg){String cls=lower(e.getClassName()),all=lower(e.getText())+" "+lower(e.getContentDescription());if(pkg.equals("com.android.packageinstaller")||pkg.equals("com.google.android.packageinstaller")||pkg.equals("com.android.permissioncontroller")||pkg.equals("com.google.android.permissioncontroller"))return true;if(!pkg.equals("com.android.settings"))return false;if(containsAny(cls,"accessibility","installedaccessibility")||(cls.contains("subsettings")&&containsAny(all,"נגישות","accessibility")))return true;if(containsAny(cls,"deviceadmin","device_admin","deviceadministrators"))return true;if(containsAny(all,"מנהלי המכשיר","מנהלי מכשירים","אפליקציות שמנהלות את המכשיר","יישומים שמנהלים את המכשיר","device administrators","device administrator","device admin apps","device admin"))return true;boolean sec=containsAny(cls,"securitysettings","securitydashboard","securitysettingsactivity","securitydashboardactivity");if(sec&&(containsAny(all,"הגדרות אבטחה","הגדרות אבטחה נוספות","אבטחה ומיקום","security & location","security and location","more security settings","security settings")||cls.contains("subsettings")||cls.contains("settings")))return true;boolean app=containsAny(cls,"appdetails","installedappdetails","manageapplications","applicationdetails","applicationinfo","appinfo");return app&&containsAny(all,"safe steps","safesteps");}
 private boolean containsAny(String s,String...v){for(String x:v)if(s.contains(x))return true;return false;} private String lower(CharSequence v){return String.valueOf(v==null?"":v).toLowerCase(Locale.ROOT);} private String lower(List<CharSequence>v){StringBuilder b=new StringBuilder();if(v!=null)for(CharSequence x:v)if(x!=null){if(b.length()>0)b.append(' ');b.append(x);}return b.toString().toLowerCase(Locale.ROOT);}
 private void blockCurrentScreen(){if(blocking||overlay!=null)return;blocking=true;showProtectionScreen();handler.postDelayed(()->performGlobalAction(GLOBAL_ACTION_BACK),10);handler.postDelayed(()->performGlobalAction(GLOBAL_ACTION_HOME),40);}
 private void showProtectionScreen(){if(wm==null){blocking=false;return;}LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER);root.setPadding(dp(28),dp(28),dp(28),dp(28));root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(7,29,64),Color.rgb(34,112,188),Color.rgb(61,46,130)}));TextView sh=label("🛡",68,true);root.addView(sh,new LinearLayout.LayoutParams(-1,dp(105)));root.addView(label("הפעולה חסומה",29,true),new LinearLayout.LayoutParams(-1,dp(60)));root.addView(label("מכשיר זה מוגן על ידי Safe Steps",17,false),new LinearLayout.LayoutParams(-1,dp(55)));TextView wait=label("המסך נסגר. יש להמתין שתי שניות…",15,false);root.addView(wait,new LinearLayout.LayoutParams(-1,dp(55)));TextView back=new TextView(this);back.setText("חזור");back.setTextSize(18);back.setTextColor(Color.WHITE);back.setGravity(Gravity.CENTER);back.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{Color.rgb(67,157,235),Color.rgb(90,105,220)});bg.setCornerRadius(dp(18));back.setBackground(bg);back.setAlpha(.45f);back.setEnabled(false);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(230),dp(58));bp.gravity=Gravity.CENTER_HORIZONTAL;bp.topMargin=dp(10);root.addView(back,bp);back.setOnClickListener(v->{performGlobalAction(GLOBAL_ACTION_HOME);removeProtectionScreen();});WindowManager.LayoutParams p=new WindowManager.LayoutParams(-1,-1,WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY,WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN|WindowManager.LayoutParams.FLAG_FULLSCREEN,PixelFormat.TRANSLUCENT);try{wm.addView(root,p);overlay=root;}catch(Exception x){blocking=false;return;}handler.postDelayed(()->{if(overlay!=root)return;back.setEnabled(true);back.setAlpha(1f);wait.setText("המסך נסגר. לחצו על חזור כדי לצאת.");},2000);}
 private TextView label(String s,float z,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}private int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private void removeProtectionScreen(){if(overlay!=null&&wm!=null){try{wm.removeView(overlay);}catch(Exception ignored){}}overlay=null;blocking=false;}public void onInterrupt(){removeProtectionScreen();}public boolean onUnbind(Intent i){removeProtectionScreen();return super.onUnbind(i);}
}
