package com.example.safesteps;
import android.app.*;import android.os.Bundle;import android.content.*;import android.graphics.Color;import android.text.InputType;import android.view.*;import android.widget.*;
public class MainActivity extends Activity{
 public static final String PREFS="safe_steps",PASSWORD="admin_password",TYPE="password_type",ENABLED="protection_enabled",PIN="pin",PATTERN="pattern";private int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private TextView txt(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER);if(b)v.setTypeface(null,1);return v;}
 protected void onCreate(Bundle b){super.onCreate(b);getSharedPreferences(PREFS,0).edit().putString(PASSWORD,getSharedPreferences(PREFS,0).getString(PASSWORD,"1234")).putString(TYPE,getSharedPreferences(PREFS,0).getString(TYPE,PIN)).apply();authenticate();}
 private void authenticate(){if(PATTERN.equals(getSharedPreferences(PREFS,0).getString(TYPE,PIN)))patternStep("כניסת מנהל",p->{if(p.equals(getSharedPreferences(PREFS,0).getString(PASSWORD,"")))manager();else{Toast.makeText(this,"תבנית שגויה",Toast.LENGTH_SHORT).show();authenticate();}});else{EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("Safe Steps").setMessage("יש להזדהות כדי להמשיך").setView(e).setCancelable(false).setPositiveButton("כניסה",(d,w)->{if(e.getText().toString().equals(getSharedPreferences(PREFS,0).getString(PASSWORD,"1234")))manager();else{Toast.makeText(this,"קוד שגוי",Toast.LENGTH_SHORT).show();authenticate();}}).show();}}
 private void manager(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(22),dp(20),dp(22),dp(20));l.addView(txt("Safe Steps",28,Color.rgb(30,75,130),true),new LinearLayout.LayoutParams(-1,dp(60)));boolean en=getSharedPreferences(PREFS,0).getBoolean(ENABLED,false);l.addView(txt(en?"🛡 ההגנה פעילה":"⚪ ההגנה כבויה",19,en?Color.rgb(30,145,90):Color.DKGRAY,true),new LinearLayout.LayoutParams(-1,dp(55)));Button t=btn(en?"כיבוי ההגנה":"הפעלת ההגנה");l.addView(t,new LinearLayout.LayoutParams(-1,dp(54)));t.setOnClickListener(v->{getSharedPreferences(PREFS,0).edit().putBoolean(ENABLED,!en).apply();manager();});Button c=btn("שינוי סיסמה");l.addView(c,new LinearLayout.LayoutParams(-1,dp(54)));c.setOnClickListener(v->chooseType());Button a=btn("אודות");l.addView(a,new LinearLayout.LayoutParams(-1,dp(54)));a.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("אודות Safe Steps").setMessage("© כל הזכויות שמורות לישראל מויאל.\nליצירת קשר פנו במייל: inm758595@gmail.com").setPositiveButton("סגירה",null).show());setContentView(l);}
 private void chooseType(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(10),dp(14),dp(10));Button pin=btn("🔢  סיסמה מספרית\nקוד אישי, מהיר ופשוט"),pat=btn("✦  סיסמת קווים\nציור תבנית על 9 נקודות"),next=btn("המשך");box.addView(pin,new LinearLayout.LayoutParams(-1,dp(88)));box.addView(pat,new LinearLayout.LayoutParams(-1,dp(88)));box.addView(next,new LinearLayout.LayoutParams(-1,dp(56)));final String[] ch={PIN};View.OnClickListener s=v->{ch[0]=v==pin?PIN:PATTERN;pin.setAlpha(ch[0].equals(PIN)?1:.55f);pat.setAlpha(ch[0].equals(PATTERN)?1:.55f);};pin.setOnClickListener(s);pat.setOnClickListener(s);pat.setAlpha(.55f);AlertDialog d=new AlertDialog.Builder(this).setTitle("בחירת סוג סיסמה").setView(box).setNegativeButton("ביטול",null).create();next.setOnClickListener(v->{d.dismiss();if(PIN.equals(ch[0]))newPin();else newPattern();});d.show();}
 private void newPin(){EditText a=new EditText(this),b=new EditText(this);a.setHint("סיסמה חדשה");b.setHint("הקלדה חוזרת");a.setInputType(2);b.setInputType(2);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.addView(a);l.addView(b);AlertDialog d=new AlertDialog.Builder(this).setTitle("סיסמה מספרית חדשה").setView(l).setNegativeButton("ביטול",null).setPositiveButton("שמירה",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String p=a.getText().toString();if(p.length()<4){a.setError("לפחות 4 ספרות");return;}if(!p.matches("[0-9]+")){a.setError("יש להזין ספרות בלבד");return;}if(!p.equals(b.getText().toString())){b.setError("הסיסמאות אינן זהות");return;}getSharedPreferences(PREFS,0).edit().putString(PASSWORD,p).putString(TYPE,PIN).apply();d.dismiss();Toast.makeText(this,"הסיסמה עודכנה",Toast.LENGTH_SHORT).show();}));d.show();}
 private void newPattern(){patternStep("ציירו סיסמה חדשה",new PatternDone(){public void go(final String p1){patternStep("ציירו שוב לאימות",new PatternDone(){public void go(String p2){if(!p1.equals(p2)){Toast.makeText(MainActivity.this,"התבניות אינן זהות",Toast.LENGTH_LONG).show();newPattern();return;}getSharedPreferences(PREFS,0).edit().putString(PASSWORD,p1).putString(TYPE,PATTERN).apply();Toast.makeText(MainActivity.this,"הסיסמה עודכנה",Toast.LENGTH_SHORT).show();}});}});}
 private interface PatternDone{void go(String pattern);}
 private void patternStep(String title,PatternDone done){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER_HORIZONTAL);c.setPadding(dp(4),dp(4),dp(4),dp(4));c.addView(txt("ציירו תבנית של לפחות 4 נקודות",15,Color.rgb(91,105,126),false),new LinearLayout.LayoutParams(-1,dp(42)));PatternLockView pv=new PatternLockView(this);c.addView(pv,new LinearLayout.LayoutParams(dp(280),dp(280)));Button ok=btn("אישור והמשך");c.addView(ok,new LinearLayout.LayoutParams(-1,dp(54)));AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setView(c).setNegativeButton("ביטול",null).create();ok.setOnClickListener(v->{String p=pv.getPattern();if(p.length()<4){Toast.makeText(this,"יש לבחור לפחות 4 נקודות",Toast.LENGTH_SHORT).show();return;}d.dismiss();done.go(p);});d.show();}
}
